### ISSUE TITLE
Mod broken after TR update

### ISSUE THREAD

**Issue by mtb-xt** [loleq2105/Ag4tr#7]
Hi! 

Thank you for your mod, can't live without NVG.

Unfortunately, after TR update, minecraft crashes on startup with the following:

```
[17/09/2021 19:49:22 PM] java.lang.ClassCastException: class dev.loleq21.gearreborn.NightvisionGoggles cannot be cast to class reborncore.common.powerSystem.RcEnergyItem (dev.loleq21.gearreborn.NightvisionGoggles and reborncore.common.powerSystem.RcEnergyItem are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @6ad59d92)
[17/09/2021 19:49:22 PM] 	at techreborn.utils.InitUtils.initPoweredItems(InitUtils.java:62)
[17/09/2021 19:49:22 PM] 	at dev.loleq21.gearreborn.NightvisionGoggles.method_7850(NightvisionGoggles.java:140)
[17/09/2021 19:49:22 PM] 	at net.minecraft.class_310.method_1546(class_310.java:775)
[17/09/2021 19:49:22 PM] 	at net.minecraft.class_310.<init>(class_310.java:576)
[17/09/2021 19:49:22 PM] 	at net.minecraft.client.main.Main.main(Main.java:179)
[17/09/2021 19:49:22 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17/09/2021 19:49:22 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[17/09/2021 19:49:22 PM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17/09/2021 19:49:22 PM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[17/09/2021 19:49:22 PM] 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[17/09/2021 19:49:22 PM] 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[17/09/2021 19:49:22 PM] 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

Full log if you need it - https://paste.atlauncher.com/view/ff052a36-6b78-4b1b-8f39-db7b221c3cc2

**Comment by loleq2105** [comment]
The latest release should have this covered: https://www.curseforge.com/minecraft/mc-mods/gearreborn/files/3462743
Let me know if it works on your side.

**Comment by mtb-xt** [comment]
Thank you, it works!
